### ISSUE TITLE
Calling `render` in `act` produces "Can't access .root on unmounted test renderer" error

### ISSUE THREAD

**Issue by dawsonc623** [testing-library/native-testing-library#91] opened 2019-12-11 14:47 UTC
- `react-native` or `expo`: react-native
- `native-testing-library` version: ^5.0.2
- `jest-preset`: @testing-library/react-native
- `react-native` version: 0.59.5
- `node` version: v10.16.1

### Relevant code or config:

```js
import React from "react";

import {
  NativeTestInstance,

  act,
  render
} from "@testing-library/react-native";

test(
  "rendering in act works",
  async () : Promise<void> =>
  {
    let baseElement : NativeTestInstance;

    act(
      () : void =>
      {
        baseElement = render(
          <div></div>
        ).baseElement;
      }
    );

    // TypeScript thinks this is being used before assigned, but the above call to act guarantees it will be assigned
    // @ts-ignore
    expect(baseElement).toMatchSnapshot();
  }
);
```

### What you did:

I ran the above test with `jest`.

### What happened:

I get this in the console:

```
yarn run v1.19.1
$ jest
 FAIL  __tests__/integration-tests/login/index.test.tsx
  ✕ rendering in act works (193ms)

  ● rendering in act works

    Can't access .root on unmounted test renderer

       99 |       () : void =>
      100 |       {
    > 101 |         baseElement = render(
          |                       ^
      102 |           <div></div>
      103 |         ).baseElement;
      104 |       }

      at Object.get [as root] (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12960:17)
      at root (node_modules/@testing-library/react-native/dist/index.js:96:54)
      at __tests__/integration-tests/login/index.test.tsx:101:23
      at fn (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12334:12)
      at batchedUpdates (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12988:18)
      at _callee$ (__tests__/integration-tests/login/index.test.tsx:98:5)
      at call (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.tryCatch [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator._invoke [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at call (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.948s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction:

Copy the test above to a test file (either a `.tsx` or strip the TypeScript-specific bits out). Then, run the test normally with `jest`.

Extra potentially-related environment bits:

```
    "@babel/core": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "@testing-library/react-native": "^5.0.2",
    "@types/jest": "^24.0.11",
    "@types/react": "^16.8.14",
    "@types/react-native": "^0.57.50",
    "@types/react-test-renderer": "^16.8.1",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3",
    "typescript": "^3.4.5"
```

### Problem description:

It is not possible to test React components that use state changes without using `act`, and it is not possible to `render` inside of `act`, or so it seems. Because of this, I cannot run the integration tests I am trying to write.

### Suggested solution:

Honestly, I am not exactly sure where this issue comes from. I did some Googling, but issues showing this error message are very sparse, and I actually get more results for the source code with the error message in it versus problems with the error itself.

Admittedly, due to the lack of information on Google, I cannot 100% say this is an issue with this library directly; only that the symptoms occur from using it.

### Can you help us fix this issue by submitting a pull request?

If I knew what the problem was and understood enough to come up with a solution (assuming this is an issue with this library), I would happily submit a PR. This is holding me up at my job, so the faster the resolution the better.

**Comment by bcarroll22** [comment] 2019-12-11 15:49
We call act automatically anytime you use render or fire events, is there a reason you're trying to call act yourself?

**Comment by dawsonc623** [comment] 2019-12-11 16:01
If I do not call `act`, I get errors saying I need to, so that is why I do it. I can grab that specific error message if you need it.

**Comment by bcarroll22** [comment] 2019-12-11 16:06
Yes can you please post the output?

**Comment by dawsonc623** [comment] 2019-12-11 16:19
The error does not come up when using `div`s, but rather when using my React Native components. It seems to be complaining about one of the library components:

```
yarn run v1.19.1
$ jest
 FAIL  __tests__/integration-tests/login/index.test.tsx
  When logging in
    if the user authenticates successfully
      ✕ the main App view is shown with the app selector up (278ms)

  ● When logging in › if the user authenticates successfully › the main App view is shown with the app selector up

    Can't access .root on unmounted test renderer

      70 |               () : void =>
      71 |               {
    > 72 |                 baseElement = render(
         |                               ^
      73 |                   <Shell
      74 |                     apps = {new Map()}
      75 |                   />

      at Object.get [as root] (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12960:17)
      at root (node_modules/@testing-library/react-native/dist/index.js:96:54)
      at __tests__/integration-tests/login/index.test.tsx:72:31
      at fn (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12334:12)
      at batchedUpdates (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12988:18)
      at _callee$ (__tests__/integration-tests/login/index.test.tsx:69:19)
      at call (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.tryCatch [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator._invoke [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at call (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)

  console.error node_modules/react-native/Libraries/YellowBox/YellowBox.js:59
    Warning: An update to ShellMain inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in ShellMain (created by Shell)
        in Shell
        in View (created by View)
        in View (created by AppContainer)
        in View (created by View)
        in View (created by AppContainer)
        in AppContainer (at src/index.js:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.851s
Ran all test suites.
error Command failed with exit code 1.
```

The only code change I did was change `div` to my `Shell` component as shown in the error message.

**Comment by bcarroll22** [comment] 2019-12-11 16:31
`Warning: An update to ShellMain inside a test was not wrapped in act(...).` this is just a warning even though it shows up as a console.error in the tests. This is usually a symptom of some sort of issue with a hook in one of your actual components, not in tests. The actual error, not being able to access `.root` on an unmounted component is probably caused by wrapping your render in act, which is causing `act` to be run multiple times.

Maybe it would help to look through some simple examples we have like [this one](https://github.com/testing-library/native-testing-library/blob/master/src/__tests__/misc.js#L9) to see simple instances where updating state works without calling `act()`? I know the warning about an update not being wrapped in act is annoying and hard to track down, but I've never seen an instance where that warning was actually coming from Testing Library itself.

**Comment by dawsonc623** [comment] 2019-12-11 16:53
Ah, I see. I removed `act` and tried it again. The tests seem to work, but the other warning messages stay (them being red threw me off). If those can be safely ignored, that should be fine. If there is a way to silence that particular error, it would help with our CI logs not getting too messy. Otherwise, I can try to manually filter it myself.

**Comment by bcarroll22** [comment] 2019-12-11 18:03
They don't cause the tests to fail, but it does usually indicate something that should be addressed in an actual component. There are ways to filter out the errors, but it may be worth it to look into the actual cause of the act error.

Going to go ahead and close this now, but good luck! 👍 💯

**Closed by bcarroll22** 2019-12-11 18:03 UTC

**Comment by dawsonc623** [comment] 2019-12-12 14:39
@bcarroll22 I think I found the source of the issue, but I am not sure if this library has any way to facilitate the case I ran into.

I am running an integration test to basically see if "redirection" works upon login. What seems to be happening is that since my code uses promises internally, my set hooks do not fire until after `render` finishes, meaning they are being fired outside of the `act` call. Without digging too far into the implementation, here is an example of what is happening:

```ts
describe(
  "while the login is in progress",
  () : void =>
  {
    let resolvePromise  : PromiseResolver<User>;

    beforeEach(
      () : void =>
      {
        loginService.login.mockReturnValue(
          new Promise(
            (
              resolve : PromiseResolver<User>
            ) : void =>
            {
              resolvePromise  = resolve;
            }
          )
        );
      }
    );

    test(
      "an activity indicator is present",
      () : void =>
      {
        const {
          baseElement,
          getByTestId
        } = render(
          <Shell
            apps  = {new Map()}
          />
        );

        getByTestId(
          "activityIndicator"
        );

        expect(baseElement).toMatchSnapshot();
      }
    );

    afterEach(
      () : void =>
      {
        console.log("before act");
        act(
          () : void =>
          {
            console.log("in act before resolve");
            resolvePromise(
              user
            );
            console.log("in act after resolve");
          }
        );
        console.log("after act");
      }
    );
  }
);
```

Internally to the `Shell` component I wrapped the set hook in another function and called `console.log` within there as well. The resulting output was this:

```
  console.log tests/integration-tests/login/index.test.tsx:98
    before act

  console.log tests/integration-tests/login/index.test.tsx:102
    in act before resolve

  console.log tests/integration-tests/login/index.test.tsx:106
    in act after resolve

  console.log tests/integration-tests/login/index.test.tsx:109
    after act

  console.log src/core/js/ui/shell/ui/main/index.tsx:58
    in 'setCurrentUser'
```

Is there a way to account for this case using this library, or is this just because of the way my code fires that makes it impossible to get the sequencing right from a testing perspective?
